[package]
name = "adb-pair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdns-sd = "0.10.4"
qr2term = "0.3.1"
rand = "0.8.5"

